/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_YIMAGE_H
#define PHP_YIMAGE_H

extern zend_module_entry yimage_module_entry;
#define phpext_yimage_ptr &yimage_module_entry

#ifdef PHP_WIN32
# define PHP_YIMAGE_API __declspec(dllexport)
#else
# define PHP_YIMAGE_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(yimage);
PHP_MSHUTDOWN_FUNCTION(yimage);
PHP_RINIT_FUNCTION(yimage);
PHP_RSHUTDOWN_FUNCTION(yimage);
PHP_MINFO_FUNCTION(yimage);

ZEND_NAMED_FUNCTION(_wrap_YImageClassify);
ZEND_NAMED_FUNCTION(_wrap_YImageEntropy);
#endif /* PHP_YIMAGE_H */
