name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login --username=lushuncheng --password Lushuncheng5005 registry.cn-beijing.aliyuncs.com
        docker pull mysql:8.4
        docker tag mysql:8.4 registry.cn-beijing.aliyuncs.com/cateye/mysql:8.4
        docker push registry.cn-beijing.aliyuncs.com/cateye/mysql:8.4
        docker pull redis:6.0
        docker tag redis:6.0 registry.cn-beijing.aliyuncs.com/cateye/redis:6.0
        docker push registry.cn-beijing.aliyuncs.com/cateye/redis:6.0
        docker pull gogs/gogs:0.12.3
        docker tag gogs/gogs:0.12.3 registry.cn-beijing.aliyuncs.com/cateye/gogs:0.12.3
        docker push registry.cn-beijing.aliyuncs.com/cateye/gogs:0.12.3
        docker pull caddy:2.4.6
        docker tag caddy:2.4.6 registry.cn-beijing.aliyuncs.com/cateye/caddy:2.4.6
        docker push registry.cn-beijing.aliyuncs.com/cateye/caddy:2.4.6
